default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: 127.0.0.1

development:
  <<: *default
  username: newApp
  password: hello123
  database: world_publico_development_new


production:
  <<: *default
  username: newApp
  password: hello123
  database: world_publico_production
